
import { Panel } from "@/lib/types";
import { PlaceHolderImages } from "@/lib/placeholder-images";

export const MOCK_PANELS: Panel[] = [
  {
    id: "1",
    name: "Roble Claro Premium",
    brand: "Arauco",
    width: 1830,
    height: 2600,
    thickness: 18,
    hasGrain: true,
    description: "Tablero de melamina sobre MDP con diseño de roble claro y textura sincronizada.",
    stock: 25,
    images: [PlaceHolderImages[0].imageUrl, PlaceHolderImages[2].imageUrl],
    mainImage: PlaceHolderImages[0].imageUrl,
    visible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Blanco Soft",
    brand: "Faplac",
    width: 2820,
    height: 1830,
    thickness: 15,
    hasGrain: false,
    description: "Melamina blanca mate de alta resistencia, ideal para interiores de placards.",
    stock: 150,
    images: [PlaceHolderImages[1].imageUrl],
    mainImage: PlaceHolderImages[1].imageUrl,
    visible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Nogal Habano",
    brand: "Masisa",
    width: 1830,
    height: 2500,
    thickness: 18,
    hasGrain: true,
    description: "Diseño clásico de nogal con vetas profundas y oscuras, acabado elegante.",
    stock: 12,
    images: [PlaceHolderImages[2].imageUrl],
    mainImage: PlaceHolderImages[2].imageUrl,
    visible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "MDF Crudo Estándar",
    brand: "Guillermina",
    width: 1830,
    height: 2600,
    thickness: 9,
    hasGrain: false,
    description: "Tablero de fibra de densidad media sin revestir, apto para pintar o laquear.",
    stock: 40,
    images: [PlaceHolderImages[3].imageUrl],
    mainImage: PlaceHolderImages[3].imageUrl,
    visible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
